server:
  port: 8085
  servlet:
    context-path: /api/v1/account

management:
  server:
    port: 8185
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /api/v1/account/actuator
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: admin
  liquibase:
    default-schema: account
    change-log: db.changelog/db.changelog-master.yaml
    enabled: ${LIQUIBASE_ENABLED:true}
    drop-first: ${LIQUIBASE_DROP_FIRST:false}
  jpa:
    hibernate:
      ddl-auto: update

swagger:
  server:
    url: http://localhost:8085/api/v1/account
    description: J0xanshi%dcepseppaspa6orkw
  api:
    title: accountDetailsApi
    description: API for managing account details
    version: 1.0.0