scrape_configs:
  - job_name: "anti-fraud"
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8186"]
        labels:
          application: "anti-fraud-app"


