spring:
  application:
    name: anti-fraud-app
  profiles:
    active: local
    swagger:
      server:
        url: http://localhost:8086/api/V1/anti-fraud
        description: "Анти-фрод API сервер"
      api:
        title: "Анти-фрод API"
        description: "API документация для анти-фрод системы"
        version: "1.0.0"

