server:
  port: 8086
  servlet:
    context-path: /api/V1/anti-fraud

management:
  server:
    port: 8186
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: password
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    default-schema: anti_fraud
    change-log: db/changelog/db.changelog-master.yaml
    enabled: ${LIQUIBASE_ENABLED:true}
    drop-first: ${LIQUIBASE_DROP_FIRST:true}
  application:
    name: anti-fraud-app

swagger:
  server:
    url: http://localhost:8086/api/V1/anti-fraud
    description: "Локальный сервер для Анти-фрод API"
  api:
    title: "Анти-фрод API"
    description: "API документация для анти-фрод системы в локальной среде"
    version: "1.0.0"



