global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'account_app'
    metrics_path: '/api/v1/account/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8185']  # потому что докер